apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: warden-validating-webhook
  namespace: validation
webhooks:
  - name: warden.validation.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    # Added rule HERE
    rules:
    - operations: ["CREATE"]
      apiGroups: ["", "apps"]
      apiVersions: ["v1"]
      resources: ["pods"]
    clientConfig:
      service:
        name: warden
        namespace: validation
        path: /validate/
      caBundle: ${CA}