apiVersion: v1
kind: PersistentVolume
metadata: 
    name: my-first-pv
spec:
    storageClassName: manual
    accessModes: 
        - ReadWriteOnce
    capacity:
        storage: 3Gi
    hostPath: 
        path: /tmp/data